//
//  QuotesModel.swift
//  quotes
//
//  Created by Wilson Wei on 11/04/2025.
//

import Foundation

struct QuotesModel {
    var quotes = [
        "Your time is limited, don't waste it living someone else's life. ― Steve Jobs",
        "The future belongs to those who believe in the possibilities of tomorrow. ― Franklin D. Roosevelt",
        "In three words I can sum up everything I've learned about life: it goes on. ― Robert Frost",
        "You know you're in love when you can't fall asleep because reality is finally better than your dreams. ― Dr. Seuss",
        "It is better to be hated for what you are than to be loved for what you are not. ― Andre Gide, Autumn Leaves",
        "Insanity is doing the same thing, over and over again, but expecting different results. ― Narcotics Anonymous",
        "You miss 100% of the shots you don’t take. – Wayne Gretzky",
        "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
        "Be yourself; everyone else is already taken. – Oscar Wilde",
        "In the middle of every difficulty lies opportunity. – Albert Einstein",
        "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
        "The only thing we have to fear is fear itself. – Franklin D. Roosevelt",
        "The journey of a thousand miles begins with one step. – Lao Tzu",
        "That which does not kill us makes us stronger. – Friedrich Nietzsche",
        "Life is what happens when you're busy making other plans. – John Lennon",
        "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
        "You must be the change you wish to see in the world. – Mahatma Gandhi",
        "The purpose of our lives is to be happy. – Dalai Lama",
        "It always seems impossible until it's done. – Nelson Mandela",
        "The only way to do great work is to love what you do. – Steve Jobs",
        "If you tell the truth, you don't have to remember anything. – Mark Twain",
        "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
        "Believe you can and you're halfway there. – Theodore Roosevelt",
        "Act as if what you do makes a difference. It does. – William James",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
        "Everything you’ve ever wanted is on the other side of fear. – George Addair",
        "You can’t use up creativity. The more you use, the more you have. – Maya Angelou",
        "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
        "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
        "Do what you can, with what you have, where you are. – Theodore Roosevelt",
        "Dream big and dare to fail. – Norman Vaughan",
        "We may encounter many defeats but we must not be defeated. – Maya Angelou",
        "The best revenge is massive success. – Frank Sinatra",
        "Strive not to be a success, but rather to be of value. – Albert Einstein",
        "Everything has beauty, but not everyone sees it. – Confucius",
        "Limit your ‘always’ and your ‘nevers.’ – Amy Poehler",
        "Nothing will work unless you do. – Maya Angelou",
        "Try to be a rainbow in someone else’s cloud. – Maya Angelou",
        "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
        "The secret of getting ahead is getting started. – Mark Twain",
        "When you know better, do better. – Maya Angelou",
        "You only live once, but if you do it right, once is enough. – Mae West",
        "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
        "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
        "It does not matter how slowly you go as long as you do not stop. – Confucius",
        "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
        "Every strike brings me closer to the next home run. – Babe Ruth",
        "An unexamined life is not worth living. – Socrates",
        "Turn your wounds into wisdom. – Oprah Winfrey",
        "Do what you feel in your heart to be right – for you’ll be criticized anyway. – Eleanor Roosevelt",
        "The best way out is always through. – Robert Frost",
        "I am not a product of my circumstances. I am a product of my decisions. – Stephen R. Covey",
        "Obsessed is just a word the lazy use to describe the dedicated. – Russell Warren",
        "If opportunity doesn’t knock, build a door. – Milton Berle",
        "Don’t wait. The time will never be just right. – Napoleon Hill",
        "Failure is the condiment that gives success its flavor. – Truman Capote",
        "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, ‘I will try again tomorrow.’ – Mary Anne Radmacher",
        "You can never cross the ocean until you have the courage to lose sight of the shore. – Christopher Columbus",
        "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
        "Do not wait for the perfect time and place to enter, for you are already onstage. – Unknown",
        "I would rather die of passion than of boredom. – Vincent van Gogh",
        "He who is not courageous enough to take risks will accomplish nothing in life. – Muhammad Ali",
        "What you do makes a difference, and you have to decide what kind of difference you want to make. – Jane Goodall",
        "In any given moment we have two options: to step forward into growth or to step back into safety. – Abraham Maslow",
        "Be not afraid of going slowly, be afraid only of standing still. – Chinese Proverb",
        "Success is stumbling from failure to failure with no loss of enthusiasm. – Winston Churchill",
        "If people are doubting how far you can go, go so far that you can’t hear them anymore. – Michele Ruiz",
        "Great things are done by a series of small things brought together. – Vincent van Gogh",
        "You will face many defeats in life, but never let yourself be defeated. – Maya Angelou",
        "Your life does not get better by chance, it gets better by change. – Jim Rohn",
        "If you’re going through hell, keep going. – Winston Churchill",
        "The mind is everything. What you think you become. – Buddha",
        "A person who never made a mistake never tried anything new. – Albert Einstein",
        "All our dreams can come true, if we have the courage to pursue them. – Walt Disney",
        "It’s not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
        "Light tomorrow with today. – Elizabeth Barrett Browning",
        "The best dreams happen when you’re awake. – Cherie Gilderbloom",
        "Stay hungry, stay foolish. – Steve Jobs",
        "Do not fear mistakes. You will know failure. Continue to reach out. – Benjamin Franklin",
        "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle",
        "Opportunities don't happen. You create them. – Chris Grosser",
        "Success is how high you bounce when you hit bottom. – George S. Patton",
        "Doubt kills more dreams than failure ever will. – Suzy Kassem",
        "It is never too late to be what you might have been. – George Eliot",
        "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown",
        "Sometimes you win, sometimes you learn. – John C. Maxwell",
        "You cannot swim for new horizons until you have courage to lose sight of the shore. – William Faulkner",
        "You are enough just as you are. – Meghan Markle",
        "Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi",
        "Don’t count the days, make the days count. – Muhammad Ali",
        "Everything you can imagine is real. – Pablo Picasso",
        "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
        "The only limits in our life are those we impose on ourselves. – Bob Proctor",
        "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne",
        "Do not let what you cannot do interfere with what you can do. – John Wooden",
        "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
        "The way to get started is to quit talking and begin doing. – Walt Disney",
        "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
        "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
        "Life is either a daring adventure or nothing at all. – Helen Keller",
        "Keep going. Everything you need will come to you at the perfect time. – Unknown",
        "Act as though it is impossible to fail. – Dorothea Brande",
        "Small deeds done are better than great deeds planned. – Peter Marshall",
        "Do not wait; the time will never be 'just right.' – Napoleon Hill",
        "You are not a drop in the ocean. You are the entire ocean in a drop. – Rumi",
        "Hustle beats talent when talent doesn’t hustle. – Ross Simmonds",
        "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou",
        "Energy and persistence conquer all things. – Benjamin Franklin",
        "Start each day with a positive thought and a grateful heart. – Roy T. Bennett",
        "The best view comes after the hardest climb. – Unknown",
        "Work hard in silence, let success make the noise. – Frank Ocean",
        "Perseverance is not a long race; it is many short races one after another. – Walter Elliot",
        "Push yourself, because no one else is going to do it for you. – Unknown",
        "Stars can't shine without darkness. – D.H. Sidebottom",
        "The comeback is always stronger than the setback. – Unknown"
    ]
}
